app_port: 8000
fastapiservice:
    user: "bellias"
    user_dir: "/home/bellias"
    group: "bellias"
    workingdir: "{{ user_dir }}/Reference-Letters-Server/main"
    execstart: "{{ user_dir }}/Reference-Letters-Server/myvenv/bin/uvicorn --access-logfile - --workers 3 --bind 0.0.0.0:8000 app.wsgi:application"
