---
test:
    hosts:
        devops-vm:
            ansible_host: 51.103.139.111
            ansible_port: 22
            ansible_ssh_user: bellias
jenkins:
    hosts:
        jenkins-server:
            ansible_host: null
            ansible_port: 22
