---
test:
    hosts:
        devops-vm #:
            #ansible_host: null
            #ansible_port: 22
            #ansible_ssh_user: null
#jenkins:
#    hosts:
#        jenkins-server:
#            ansible_host: null
#            ansible_port: 22
