---
- name: install nginx and ssl certificates in jenkins
  hosts: all

  tasks:

  - name: install and configure nginx
    block:

    - name: "APT - install nginx"
      apt:
        name: nginx
        update_cache: yes

    - name: copy nginx conf file
      template:
        src: ../files/nginx/jenkins.nginx.j2
        dest: "/etc/nginx/sites-available/jenkins"

    # - name: copy nginx https conf file
    #   template:
    #     src: ../files/nginx/jenkins.https.nginx.j2
    #     dest: "/etc/nginx/sites-available/jenkinsssl"

    # - name: copy certificates
    #   copy:
    #     src: "{{item}}"
    #     dest: /etc/ssl/private/
    #   with_items:
    #     - ../files/certs/jenkins/certificate.crt
    #     - ../files/certs/jenkins/private.key

    - name: enable jenkins site in nginx
      file:
        src: "/etc/nginx/sites-available/jenkins"
        dest: "/etc/nginx/sites-enabled/jenkins"
        state: link
      notify: restart nginx

    # - name: enable jenkinsssl site in nginx
    #   file:
    #     src: "/etc/nginx/sites-available/jenkinsssl"
    #     dest: "/etc/nginx/sites-enabled/jenkinsssl"
    #     state: link
    #   notify: restart nginx

    - name: de-activate default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx

    become: yes
    become_user: root

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes
