---
- hosts: all
  tasks:
  - debug:
      msg: |
           "Operating System is {{ hostvars[inventory_hostname].ansible_distribution }}"
           "Operating System major version is {{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
           "Operating System minor version is {{ hostvars[inventory_hostname].ansible_distribution_version }}"
  
  - name: Retrieve the list of home directories
    command: ls /home
    register: home_dirs

  - name: print home dirs object
    debug:
      msg: "{{home_dirs}}"

  - name: print home dirs
    debug:
      msg: "{{home_dirs.stdout}}"
  
  - name: Check Date with Shell command
    shell:
        "date"
    register: datecmd

  - debug: msg="{{datecmd.stdout}}"

  - name: Dir list and write to file
    shell:
        " ls -lrt /home '{print $9}'|sed '/^$/d' > /tmp/dirlist.txt "
    register: lsout

  - name: Display the file
    shell: cat /tmp/dirlist.txt
    register: displaylist
    
  - debug: msg="{{displaylist.stdout_lines}}"
